---
title: Wiki
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: and.rey.q@yandex.ru
description: Welocome to wiki page.
baseurl: jekyll
url: https://kuznetsovandrey76.github.io/
github_username: kuznetsovandrey76
markdown: kramdown
theme: minima
plugins:
- jekyll-feed
