---
title: Andrey Kuznetsov | Wiki
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: and.rey.q@yandex.ru
description: Welocome to Andrey Kuznetsov wiki blog.
baseurl: jekyll
url: http://kuznetsovandrey76.ru/
github_username: kuznetsovandrey76
markdown: kramdown
theme: minima
plugins:
- jekyll-feed
